project:
  type: website

website:
  announcement: 
    icon: exclamation-triangle
    dismissable: false
    content: "**Alert** - This website is under construction. Please be aware."
    type: primary
    position: below-navbar 
  title: "TJ"
  description: The personal website of Tiago Jacinto
  site-url: https://tiagojacinto.net
  navbar:
    background: dark
    search: false
    left:
      - href: index.qmd
        text: Home
    right: 
      - icon: mastodon
        href: https://mastodon.social/@tiagojnet
      - icon: instagram
        href: https://www.instagram.com/tiagojnet/  

format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
    toc: true



